"""Trackpad monitoring and controller recovery subsystem."""

from .constants import *  # noqa: F403
from .controller import (
    find_steam_deck_hidraw,
    find_steam_deck_usb_device,
    power_cycle_steam_deck_controller,
    reconcile_steam_deck_controller_authorization,
    reinitialize_steam_deck_trackpad_driver,
)
from .models import TrackpadCaptureSummary, TrackpadMetricsSample
from .monitor import LOGGER, TrackpadMetricsMonitor
from .parsing import parse_trackpad_metrics_report


__all__ = [
    'AUTO_CAPTURE_COOLDOWN_SECONDS',
    'AUTO_CAPTURE_DELAY_SECONDS',
    'AUTO_CAPTURE_TOUCHES',
    'AUTO_CAPTURE_WINDOW_SECONDS',
    'CAPTURE_VERSION',
    'CLICK_PRESSURE_THRESHOLD',
    'CONTROLLER_RECONCILE_INTERVAL_SECONDS',
    'DEFAULT_RETENTION_SECONDS',
    'DEFAULT_SAMPLE_RATE_HZ',
    'IDLE_REPORT_BATCH_INTERVAL_SECONDS',
    'JOURNAL_FLUSH_INTERVAL_SECONDS',
    'JOURNAL_PREFIX',
    'JOURNAL_REASON',
    'JOURNAL_SUFFIX',
    'JOURNAL_WINDOW_SECONDS',
    'LEFT_PAD_PRESSED',
    'LEFT_PAD_PRESSURE_OFFSET',
    'LEFT_PAD_TOUCHED',
    'LEFT_PAD_X_OFFSET',
    'LOGGER',
    'MAX_AUTOMATIC_CAPTURES',
    'MAX_JOURNAL_WINDOWS',
    'MAX_REPORT_BATCH_SIZE',
    'MAX_WINDOW_SAMPLES',
    'MIN_REPORT_SIZE',
    'MONITOR_MAINTENANCE_INTERVAL_SECONDS',
    'RECOVERY_ABNORMAL_PRESSURE',
    'RECOVERY_ARM_TIMEOUT_SECONDS',
    'RECOVERY_COOLDOWN_SECONDS',
    'RECOVERY_IDLE_SECONDS',
    'RECOVERY_IDLE_REPORT_BATCH_INTERVAL_SECONDS',
    'RECOVERY_MOTION_CLICK_WINDOW_SECONDS',
    'RECOVERY_MOTION_DISTANCE',
    'RECOVERY_MOTION_STEP',
    'RECOVERY_RESULT_TIMEOUT_SECONDS',
    'RECOVERY_SUSTAINED_PRESSURE_SECONDS',
    'REPORT_HEADER',
    'REPORT_SEQUENCE_OFFSET',
    'RIGHT_PAD_PRESSED',
    'RIGHT_PAD_PRESSURE_OFFSET',
    'RIGHT_PAD_TOUCHED',
    'RIGHT_PAD_X_OFFSET',
    'STEAM_DECK_HID_ID',
    'TRACKPAD_CONTROL_MASK',
    'TrackpadCaptureSummary',
    'TrackpadMetricsMonitor',
    'TrackpadMetricsSample',
    'find_steam_deck_hidraw',
    'find_steam_deck_usb_device',
    'parse_trackpad_metrics_report',
    'power_cycle_steam_deck_controller',
    'reconcile_steam_deck_controller_authorization',
    'reinitialize_steam_deck_trackpad_driver',
]
