"""Trackpad protocol and monitor tuning constants."""

STEAM_DECK_HID_ID = "0003:000028DE:00001205"
REPORT_HEADER = b"\x01\x00\x09"
REPORT_SEQUENCE_OFFSET = 4
LEFT_PAD_PRESSED = 0x00020000
RIGHT_PAD_PRESSED = 0x00040000
LEFT_PAD_TOUCHED = 0x00080000
RIGHT_PAD_TOUCHED = 0x00100000
TRACKPAD_CONTROL_MASK = (
    LEFT_PAD_PRESSED
    | RIGHT_PAD_PRESSED
    | LEFT_PAD_TOUCHED
    | RIGHT_PAD_TOUCHED
)
LEFT_PAD_X_OFFSET = 16
RIGHT_PAD_X_OFFSET = 20
LEFT_PAD_PRESSURE_OFFSET = 56
RIGHT_PAD_PRESSURE_OFFSET = 58
MIN_REPORT_SIZE = RIGHT_PAD_PRESSURE_OFFSET + 2
DEFAULT_RETENTION_SECONDS = 15 * 60
DEFAULT_SAMPLE_RATE_HZ = 20
MAX_WINDOW_SAMPLES = 1_000
CLICK_PRESSURE_THRESHOLD = 2_000
AUTO_CAPTURE_TOUCHES = 2
AUTO_CAPTURE_WINDOW_SECONDS = 12
AUTO_CAPTURE_DELAY_SECONDS = 5
AUTO_CAPTURE_COOLDOWN_SECONDS = 5 * 60
MAX_AUTOMATIC_CAPTURES = 10
RECOVERY_MOTION_DISTANCE = 800
RECOVERY_MOTION_STEP = 80
RECOVERY_MOTION_CLICK_WINDOW_SECONDS = 0.2
RECOVERY_IDLE_SECONDS = 1.0
RECOVERY_ARM_TIMEOUT_SECONDS = 20
RECOVERY_COOLDOWN_SECONDS = 30
RECOVERY_ABNORMAL_PRESSURE = 6_000
RECOVERY_SUSTAINED_PRESSURE_SECONDS = 0.75
RECOVERY_RESULT_TIMEOUT_SECONDS = 15
MONITOR_MAINTENANCE_INTERVAL_SECONDS = 0.25
# Metrics are retained at 20 Hz, so polling an idle stream faster only
# creates redundant monitor wakeups.
IDLE_REPORT_BATCH_INTERVAL_SECONDS = 0.05
# hidraw buffers 64 reports per reader. The Deck emits 250 reports/s,
# leaving enough headroom to preserve every transition at 5 Hz while
# automatic recovery is the monitor's only active consumer.
RECOVERY_IDLE_REPORT_BATCH_INTERVAL_SECONDS = 0.2
MAX_REPORT_BATCH_SIZE = 64
CONTROLLER_RECONCILE_INTERVAL_SECONDS = 5
JOURNAL_FLUSH_INTERVAL_SECONDS = 3 * 60
JOURNAL_WINDOW_SECONDS = 15 * 60
MAX_JOURNAL_WINDOWS = 3
JOURNAL_REASON = "rolling-journal"
JOURNAL_PREFIX = "rolling-"
JOURNAL_SUFFIX = ".jsonl"
CAPTURE_VERSION = 1
