"""Nested Desktop input bridge subsystem."""

from .bindings import (
    InputBindingTranslator, TrackpadTranslator, decode_gamescope_display,
    normalize_nested_desktop_bindings, parse_trackpad_report,
    prioritize_focus_app, should_forward_back_button, should_forward_pointer,
)
from .cli import main, run_worker
from .clipboard import (
    CLIPBOARD_IMAGE_MIME_TYPES, CLIPBOARD_MAX_BYTES,
    CLIPBOARD_TEXT_MAX_BYTES, ClipboardContent,
    X11ClipboardEndpoint,
)
from .clipboard_bridge import NestedDesktopClipboardBridge
from .constants import *  # noqa: F403
from .cursor import (
    NestedDesktopCursorOverlay, cursor_alpha_mask, outlined_cursor_snapshot,
    scaled_cursor_snapshot,
)
from .discovery import (
    ensure_nested_wayland_alias, find_nested_desktop_session,
    find_rustdesk_joystick, find_rustdesk_keyboard, find_steam_deck_hidraw,
    find_steam_deck_touchscreen, process_uses_proton,
    remove_nested_wayland_alias,
)
from .eis import EisConnection
from .gamescope import (
    GamescopeCursorCompositor, GamescopePointerInterceptor,
    set_gamescope_cursor_composite,
)
from .models import (
    BindingUpdate, CursorSnapshot, JoystickEvent, LinuxInputEvent,
    NestedDesktopSession, PointerUpdate, TouchFrame, TouchUpdate,
    TrackpadState,
)
from .pointer_capture import (
    CapturedPointerUpdate, GamescopePointerCapture,
    GamescopePointerTranslator,
)
from .runtime import LOGGER, NestedDesktopMouseRuntime
from .rustdesk import (
    RustDeskMouseTranslator, RustDeskRelayTranslator, RustDeskScrollInertia,
    encode_rustdesk_ipc_frame, parse_joystick_events,
    parse_linux_input_events, query_rustdesk_video_connection_count,
    receive_rustdesk_ipc_frame,
)
from .supervisor import NestedDesktopMouseSupervisor
from .touch import (
    TouchscreenInertia, TouchscreenInertiaConfig, TouchscreenParser,
    TouchscreenReader,
)
from .x11 import X11Connection

__all__ = [
    'ACTION_HIDE_KEYBOARD',
    'ACTION_MOUSE_LEFT',
    'ACTION_MOUSE_MIDDLE',
    'ACTION_MOUSE_RIGHT',
    'ACTION_NONE',
    'ACTION_SHOW_KEYBOARD',
    'BACK_BUTTON',
    'BTN_LEFT',
    'BTN_MIDDLE',
    'BTN_RIGHT',
    'BUTTON_SOURCE_MASKS',
    'BindingUpdate',
    'CLIPBOARD_MAX_BYTES',
    'CLIPBOARD_IMAGE_MIME_TYPES',
    'CLIPBOARD_TEXT_MAX_BYTES',
    'ClipboardContent',
    'CapturedPointerUpdate',
    'CURSOR_IMAGE_REFRESH_INTERVAL',
    'CURSOR_RENDER_MAX_DIMENSION',
    'CURSOR_OUTLINE_PIXEL',
    'CURSOR_OUTLINE_RADIUS',
    'CursorSnapshot',
    'DEFAULT_NESTED_DESKTOP_BINDINGS',
    'DISCOVERY_INTERVAL',
    'EIS_KEY_CODES',
    'EI_DEVICE_CAP_BUTTON',
    'EI_DEVICE_CAP_KEYBOARD',
    'EI_DEVICE_CAP_POINTER',
    'EI_DEVICE_CAP_POINTER_ABSOLUTE',
    'EI_DEVICE_CAP_SCROLL',
    'EI_DEVICE_CAP_TOUCH',
    'EI_EVENT_DEVICE_ADDED',
    'EI_EVENT_DEVICE_PAUSED',
    'EI_EVENT_DEVICE_REMOVED',
    'EI_EVENT_DEVICE_RESUMED',
    'EI_EVENT_DISCONNECT',
    'EI_EVENT_SEAT_ADDED',
    'EisConnection',
    'FOCUS_CHECK_INTERVAL',
    'FOCUS_SNAPSHOT_FALLBACK_INTERVAL',
    'GAMESCOPE_FOCUS_EVENT_PROPERTIES',
    'GAMESCOPE_FOCUS_PROPERTIES',
    'GAMESCOPE_POINTER_HID_SUPPRESSION_GRACE',
    'GAMESCOPE_POINTER_RELAY_DELAY',
    'GamescopeCursorCompositor',
    'GamescopePointerCapture',
    'GamescopePointerInterceptor',
    'GamescopePointerTranslator',
    'IDLE_INPUT_FRAME_INTERVAL',
    'INPUT_FRAME_INTERVAL',
    'InputBindingTranslator',
    'JOYSTICK_AXIS_MIN',
    'JOYSTICK_AXIS_SPAN',
    'JOYSTICK_EVENT_AXIS',
    'JOYSTICK_EVENT_BUTTON',
    'JOYSTICK_EVENT_INIT',
    'JOYSTICK_EVENT_SIZE',
    'JoystickEvent',
    'KEYBOARD_DEVICE_GRACE',
    'KEYBOARD_PORTAL_CAPABILITY',
    'LEFT_PAD_PRESSED',
    'LEFT_PAD_TOUCHED',
    'LEFT_PAD_X_OFFSET',
    'LEFT_PAD_Y_OFFSET',
    'LEFT_STICK_PRESS_THRESHOLD',
    'LEFT_STICK_RELEASE_THRESHOLD',
    'LEFT_TRIGGER',
    'LEGACY_RUSTDESK_POINTER_SYNC_MARKER',
    'LINUX_ABS_X',
    'LINUX_ABS_Y',
    'LINUX_ABS_MT_POSITION_X',
    'LINUX_ABS_MT_POSITION_Y',
    'LINUX_ABS_MT_SLOT',
    'LINUX_ABS_MT_TRACKING_ID',
    'LINUX_EV_ABS',
    'LINUX_EV_KEY',
    'LINUX_EV_REL',
    'LINUX_EV_SYN',
    'LINUX_INPUT_EVENT',
    'LINUX_REL_HWHEEL',
    'LINUX_REL_WHEEL',
    'LINUX_SYN_REPORT',
    'LinuxInputEvent',
    'LOGGER',
    'MAX_TRACKPAD_DELTA',
    'MOUSE_BINDING_ACTIONS',
    'MOUSE_SCALE',
    'NESTED_DESKTOP_BINDING_ACTIONS',
    'NESTED_DESKTOP_BINDING_SOURCES',
    'NestedDesktopCursorOverlay',
    'NestedDesktopClipboardBridge',
    'NestedDesktopMouseRuntime',
    'NestedDesktopMouseSupervisor',
    'NestedDesktopSession',
    'POINTER_INERTIA_DECAY',
    'POINTER_INERTIA_START',
    'POINTER_INERTIA_STOP',
    'POINTER_PORTAL_CAPABILITY',
    'POINTER_VELOCITY_BLEND',
    'PointerUpdate',
    'REPORT_HEADER',
    'RIGHT_PAD_PRESSED',
    'RIGHT_PAD_PRESSURE_OFFSET',
    'RIGHT_PAD_PRESS_THRESHOLD',
    'RIGHT_PAD_RELEASE_THRESHOLD',
    'RIGHT_PAD_TOUCHED',
    'RIGHT_PAD_X_OFFSET',
    'RIGHT_PAD_Y_OFFSET',
    'RIGHT_STICK_DEADZONE',
    'RIGHT_STICK_MAX_SPEED',
    'RIGHT_TRIGGER',
    'RUSTDESK_ABS_MAX_X',
    'RUSTDESK_ABS_MAX_Y',
    'RUSTDESK_ACTIVE_CONNECTION_CHECK_INTERVAL',
    'RUSTDESK_CONNECTION_CHECK_INTERVAL',
    'RUSTDESK_CONNECTION_STALE_GRACE',
    'RUSTDESK_FOCUS_REQUEST_COOLDOWN',
    'RUSTDESK_IPC_MAX_FRAME',
    'RUSTDESK_IPC_TIMEOUT',
    'RUSTDESK_KEYBOARD_NAME',
    'RUSTDESK_MOUSE_NAME',
    'RUSTDESK_POINTER_RELAY_SOCKET',
    'RUSTDESK_SCROLL_INERTIA_BURST_GAP',
    'RUSTDESK_SCROLL_INERTIA_DECAY',
    'RUSTDESK_SCROLL_INERTIA_DELAY',
    'RUSTDESK_SCROLL_INERTIA_GAIN',
    'RUSTDESK_SCROLL_INERTIA_MIN_EVENTS',
    'RUSTDESK_SCROLL_INERTIA_RETAIN',
    'RUSTDESK_SCROLL_INERTIA_STOP',
    'RUSTDESK_SCROLL_UNIT',
    'RustDeskMouseTranslator',
    'RustDeskRelayTranslator',
    'RustDeskScrollInertia',
    'SCROLL_EMIT_THRESHOLD',
    'SCROLL_INERTIA_DECAY',
    'SCROLL_INERTIA_START',
    'SCROLL_INERTIA_STOP',
    'SCROLL_SCALE',
    'SCROLL_START_DEADZONE',
    'SCROLL_VELOCITY_BLEND',
    'STEAM_DECK_HID_ID',
    'STEAM_DECK_TOUCHSCREEN_NAMES',
    'STEAM_UI_APP_ID',
    'TOUCH_PORTAL_CAPABILITY',
    'TouchFrame',
    'TouchUpdate',
    'TouchscreenInertia',
    'TouchscreenInertiaConfig',
    'TouchscreenParser',
    'TouchscreenReader',
    'TrackpadState',
    'TrackpadTranslator',
    'X11Connection',
    'X11ClipboardEndpoint',
    'X11_EVENT_LONGS',
    'X11_PROPERTY_CHANGE_MASK',
    'X11_PROPERTY_NOTIFY',
    'cursor_alpha_mask',
    'decode_gamescope_display',
    'encode_rustdesk_ipc_frame',
    'ensure_nested_wayland_alias',
    'find_nested_desktop_session',
    'find_rustdesk_joystick',
    'find_rustdesk_keyboard',
    'find_steam_deck_hidraw',
    'find_steam_deck_touchscreen',
    'main',
    'normalize_nested_desktop_bindings',
    'outlined_cursor_snapshot',
    'scaled_cursor_snapshot',
    'parse_joystick_events',
    'parse_linux_input_events',
    'parse_trackpad_report',
    'prioritize_focus_app',
    'process_uses_proton',
    'query_rustdesk_video_connection_count',
    'receive_rustdesk_ipc_frame',
    'remove_nested_wayland_alias',
    'run_worker',
    'set_gamescope_cursor_composite',
    'should_forward_back_button',
    'should_forward_pointer',
]
