"""Nested Desktop protocol, input, and timing constants."""

from pathlib import Path
import struct


STEAM_DECK_HID_ID = "0003:000028DE:00001205"
STEAM_DECK_TOUCHSCREEN_NAMES = frozenset(
    (
        "FTSC1000:00 2808:1015",
        "FTS3528:00 2808:1015",
    )
)
STEAM_UI_APP_ID = 769
REPORT_HEADER = b"\x01\x00\x09"
RIGHT_TRIGGER = 0x00000001
LEFT_TRIGGER = 0x00000002
BACK_BUTTON = 0x00000020
LEFT_PAD_PRESSED = 0x00020000
RIGHT_PAD_PRESSED = 0x00040000
LEFT_PAD_TOUCHED = 0x00080000
RIGHT_PAD_TOUCHED = 0x00100000
LEFT_PAD_X_OFFSET = 16
LEFT_PAD_Y_OFFSET = 18
RIGHT_PAD_X_OFFSET = 20
RIGHT_PAD_Y_OFFSET = 22
RIGHT_PAD_PRESSURE_OFFSET = 58
RIGHT_PAD_PRESS_THRESHOLD = 2_000
RIGHT_PAD_RELEASE_THRESHOLD = 1_000
MAX_TRACKPAD_DELTA = 12_000
MOUSE_SCALE = 0.008
SCROLL_SCALE = 0.005
SCROLL_START_DEADZONE = 480
SCROLL_EMIT_THRESHOLD = 48
POINTER_VELOCITY_BLEND = 0.55
POINTER_INERTIA_DECAY = 0.90
POINTER_INERTIA_START = 4.0
POINTER_INERTIA_STOP = 0.15
SCROLL_VELOCITY_BLEND = 0.55
SCROLL_INERTIA_DECAY = 0.90
SCROLL_INERTIA_START = 2.0
SCROLL_INERTIA_STOP = 0.01
RIGHT_STICK_DEADZONE = 8_000
RIGHT_STICK_MAX_SPEED = 18.0
INPUT_FRAME_INTERVAL = 1 / 60
IDLE_INPUT_FRAME_INTERVAL = 1 / 30
TOUCH_INERTIA_FRAME_INTERVAL = 1 / 60
TOUCH_INERTIA_VELOCITY_BLEND = 0.55
TOUCH_INERTIA_STOP_SPEED = 0.35
TOUCH_INERTIA_MAX_SPEED = 36.0
TOUCH_INERTIA_MIN_EFFICIENCY = 0.72
TOUCH_INERTIA_MIN_ALIGNMENT = 0.70
TOUCH_INERTIA_MAX_RELEASE_GAP = 0.09
TOUCH_DISPLAY_WIDTH = 1280
TOUCH_DISPLAY_HEIGHT = 800
TOUCH_INERTIA_DEFAULT_DURATION_MS = 600
TOUCH_INERTIA_MIN_DURATION_MS = 150
TOUCH_INERTIA_MAX_DURATION_MS = 1_200
TOUCH_INERTIA_DEFAULT_START_SPEED = 420
TOUCH_INERTIA_MIN_START_SPEED = 180
TOUCH_INERTIA_MAX_START_SPEED = 1_200
TOUCH_INERTIA_DEFAULT_MIN_DISTANCE = 36
TOUCH_INERTIA_MIN_DISTANCE = 16
TOUCH_INERTIA_MAX_DISTANCE = 120
FOCUS_CHECK_INTERVAL = 0.25
FOCUS_SNAPSHOT_FALLBACK_INTERVAL = 0.5
DISCOVERY_INTERVAL = 5.0
CURSOR_IMAGE_REFRESH_INTERVAL = 0.25
CURSOR_OUTLINE_RADIUS = 1
CURSOR_OUTLINE_PIXEL = 0xFFFFFFFF
KEYBOARD_DEVICE_GRACE = 0.5
RUSTDESK_MOUSE_NAME = "mouce-library-fake-mouse"
RUSTDESK_POINTER_RELAY_SOCKET = Path(
    "/run/user/1000/4deus-mod-rustdesk-pointer-relay.sock"
)
RUSTDESK_CONNECTION_CHECK_INTERVAL = 0.5
RUSTDESK_ACTIVE_CONNECTION_CHECK_INTERVAL = 2.0
RUSTDESK_CONNECTION_STALE_GRACE = 2.0
RUSTDESK_FOCUS_REQUEST_COOLDOWN = 1.0
RUSTDESK_IPC_TIMEOUT = 0.01
RUSTDESK_IPC_MAX_FRAME = 4_096
RUSTDESK_KEYBOARD_NAME = "RustDesk UInput Keyboard"
RUSTDESK_SCROLL_UNIT = 90
RUSTDESK_SCROLL_INERTIA_BURST_GAP = 0.14
RUSTDESK_SCROLL_INERTIA_DELAY = 0.05
RUSTDESK_SCROLL_INERTIA_MIN_EVENTS = 3
RUSTDESK_SCROLL_INERTIA_RETAIN = 0.35
RUSTDESK_SCROLL_INERTIA_GAIN = 0.45
RUSTDESK_SCROLL_INERTIA_DECAY = 0.82
RUSTDESK_SCROLL_INERTIA_STOP = 4.0
LEGACY_RUSTDESK_POINTER_SYNC_MARKER = Path(
    "/run/user/1000/4deus-mod-rustdesk-pointer-sync"
)
JOYSTICK_EVENT_SIZE = 8
JOYSTICK_EVENT_BUTTON = 0x01
JOYSTICK_EVENT_AXIS = 0x02
JOYSTICK_EVENT_INIT = 0x80
JOYSTICK_AXIS_MIN = -32_767
JOYSTICK_AXIS_SPAN = 65_534
LINUX_INPUT_EVENT = struct.Struct("@llHHi")
LINUX_EV_SYN = 0
LINUX_EV_KEY = 1
LINUX_EV_REL = 2
LINUX_EV_ABS = 3
LINUX_SYN_REPORT = 0
LINUX_REL_HWHEEL = 6
LINUX_REL_WHEEL = 8
LINUX_ABS_X = 0
LINUX_ABS_Y = 1
LINUX_ABS_MT_SLOT = 47
LINUX_ABS_MT_POSITION_X = 53
LINUX_ABS_MT_POSITION_Y = 54
LINUX_ABS_MT_TRACKING_ID = 57
RUSTDESK_ABS_MAX_X = 1280
RUSTDESK_ABS_MAX_Y = 800
X11_PROPERTY_CHANGE_MASK = 1 << 22
X11_PROPERTY_NOTIFY = 28
X11_EVENT_LONGS = 24
GAMESCOPE_FOCUS_PROPERTIES = (
    "GAMESCOPE_FOCUSED_APP",
    "GAMESCOPE_FOCUSED_APP_GFX",
    "GAMESCOPE_MOUSE_FOCUS_DISPLAY",
    "GAMESCOPE_FOCUSABLE_APPS",
)
GAMESCOPE_FOCUS_EVENT_PROPERTIES = (
    "GAMESCOPECTRL_BASELAYER_APPID",
    "GAMESCOPECTRL_BASELAYER_WINDOW",
)
EI_DEVICE_CAP_POINTER = 1 << 0
EI_DEVICE_CAP_POINTER_ABSOLUTE = 1 << 1
EI_DEVICE_CAP_KEYBOARD = 1 << 2
EI_DEVICE_CAP_TOUCH = 1 << 3
EI_DEVICE_CAP_SCROLL = 1 << 4
EI_DEVICE_CAP_BUTTON = 1 << 5
EI_EVENT_DISCONNECT = 2
EI_EVENT_SEAT_ADDED = 3
EI_EVENT_DEVICE_ADDED = 5
EI_EVENT_DEVICE_REMOVED = 6
EI_EVENT_DEVICE_PAUSED = 7
EI_EVENT_DEVICE_RESUMED = 8
BTN_LEFT = 0x110
BTN_RIGHT = 0x111
BTN_MIDDLE = 0x112
KEYBOARD_PORTAL_CAPABILITY = 1
POINTER_PORTAL_CAPABILITY = 2
TOUCH_PORTAL_CAPABILITY = 4
LEFT_STICK_PRESS_THRESHOLD = 16_000
LEFT_STICK_RELEASE_THRESHOLD = 12_000
ACTION_NONE = "none"
ACTION_SHOW_KEYBOARD = "SHOW_KEYBOARD"
ACTION_HIDE_KEYBOARD = "HIDE_KEYBOARD"
ACTION_MOUSE_LEFT = "MOUSE_LEFT"
ACTION_MOUSE_RIGHT = "MOUSE_RIGHT"
ACTION_MOUSE_MIDDLE = "MOUSE_MIDDLE"
MOUSE_BINDING_ACTIONS = frozenset(
    (
        ACTION_MOUSE_LEFT,
        ACTION_MOUSE_RIGHT,
        ACTION_MOUSE_MIDDLE,
    )
)
EIS_KEY_CODES = {
    "KEY_ESC": 1,
    "KEY_1": 2,
    "KEY_2": 3,
    "KEY_3": 4,
    "KEY_4": 5,
    "KEY_5": 6,
    "KEY_6": 7,
    "KEY_7": 8,
    "KEY_8": 9,
    "KEY_9": 10,
    "KEY_0": 11,
    "KEY_MINUS": 12,
    "KEY_EQUAL": 13,
    "KEY_BACKSPACE": 14,
    "KEY_TAB": 15,
    "KEY_Q": 16,
    "KEY_W": 17,
    "KEY_E": 18,
    "KEY_R": 19,
    "KEY_T": 20,
    "KEY_Y": 21,
    "KEY_U": 22,
    "KEY_I": 23,
    "KEY_O": 24,
    "KEY_P": 25,
    "KEY_LEFTBRACE": 26,
    "KEY_RIGHTBRACE": 27,
    "KEY_ENTER": 28,
    "KEY_LEFTCTRL": 29,
    "KEY_A": 30,
    "KEY_S": 31,
    "KEY_D": 32,
    "KEY_F": 33,
    "KEY_G": 34,
    "KEY_H": 35,
    "KEY_J": 36,
    "KEY_K": 37,
    "KEY_L": 38,
    "KEY_SEMICOLON": 39,
    "KEY_APOSTROPHE": 40,
    "KEY_GRAVE": 41,
    "KEY_LEFTSHIFT": 42,
    "KEY_BACKSLASH": 43,
    "KEY_Z": 44,
    "KEY_X": 45,
    "KEY_C": 46,
    "KEY_V": 47,
    "KEY_B": 48,
    "KEY_N": 49,
    "KEY_M": 50,
    "KEY_COMMA": 51,
    "KEY_DOT": 52,
    "KEY_SLASH": 53,
    "KEY_LEFTALT": 56,
    "KEY_SPACE": 57,
    "KEY_F1": 59,
    "KEY_F2": 60,
    "KEY_F3": 61,
    "KEY_F4": 62,
    "KEY_F5": 63,
    "KEY_F6": 64,
    "KEY_F7": 65,
    "KEY_F8": 66,
    "KEY_F9": 67,
    "KEY_F10": 68,
    "KEY_F11": 87,
    "KEY_F12": 88,
    "KEY_HOME": 102,
    "KEY_UP": 103,
    "KEY_PAGEUP": 104,
    "KEY_LEFT": 105,
    "KEY_RIGHT": 106,
    "KEY_END": 107,
    "KEY_DOWN": 108,
    "KEY_PAGEDOWN": 109,
    "KEY_INSERT": 110,
    "KEY_DELETE": 111,
    "KEY_LEFTMETA": 125,
}
NESTED_DESKTOP_BINDING_SOURCES = (
    "a",
    "b",
    "x",
    "y",
    "dpadUp",
    "dpadRight",
    "dpadLeft",
    "dpadDown",
    "leftStickUp",
    "leftStickRight",
    "leftStickLeft",
    "leftStickDown",
    "view",
    "menu",
    "l1",
    "r1",
    "l2",
    "r2",
    "l3",
    "r3",
    "l4",
    "r4",
    "l5",
    "r5",
    "leftPadClick",
    "rightPadClick",
)
DEFAULT_NESTED_DESKTOP_BINDINGS = {
    "a": "KEY_ENTER",
    "b": "KEY_ESC",
    "x": ACTION_SHOW_KEYBOARD,
    "y": "KEY_SPACE",
    "dpadUp": "KEY_UP",
    "dpadRight": "KEY_RIGHT",
    "dpadLeft": "KEY_LEFT",
    "dpadDown": "KEY_DOWN",
    "leftStickUp": "KEY_UP",
    "leftStickRight": "KEY_RIGHT",
    "leftStickLeft": "KEY_LEFT",
    "leftStickDown": "KEY_DOWN",
    "view": "KEY_ESC",
    "menu": "KEY_TAB",
    "l1": "KEY_LEFTCTRL",
    "r1": "KEY_LEFTALT",
    "l2": ACTION_MOUSE_RIGHT,
    "r2": ACTION_MOUSE_LEFT,
    "l3": ACTION_NONE,
    "r3": ACTION_MOUSE_LEFT,
    "l4": "KEY_LEFTSHIFT",
    "r4": "KEY_PAGEUP",
    "l5": "KEY_LEFTMETA",
    "r5": "KEY_PAGEDOWN",
    "leftPadClick": ACTION_MOUSE_MIDDLE,
    "rightPadClick": ACTION_MOUSE_LEFT,
}
NESTED_DESKTOP_BINDING_ACTIONS = frozenset(
    (
        ACTION_NONE,
        ACTION_SHOW_KEYBOARD,
        ACTION_MOUSE_LEFT,
        ACTION_MOUSE_RIGHT,
        ACTION_MOUSE_MIDDLE,
        *EIS_KEY_CODES,
    )
)
BUTTON_SOURCE_MASKS = {
    "r2": 1 << 0,
    "l2": 1 << 1,
    "r1": 1 << 2,
    "l1": 1 << 3,
    "y": 1 << 4,
    "b": 1 << 5,
    "x": 1 << 6,
    "a": 1 << 7,
    "dpadUp": 1 << 8,
    "dpadRight": 1 << 9,
    "dpadLeft": 1 << 10,
    "dpadDown": 1 << 11,
    "view": 1 << 12,
    "menu": 1 << 14,
    "l5": 1 << 15,
    "r5": 1 << 16,
    "leftPadClick": 1 << 17,
    "rightPadClick": 1 << 18,
    "l3": 1 << 22,
    "r3": 1 << 26,
    "l4": 1 << 41,
    "r4": 1 << 42,
}
